basePath: /
host: localhost:8080
info:
  contact:
    email: sadeg.r1@gmail.com
    name: Sadiq Rahmati
  description: Yet another image proxy
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Rigel Api
  version: 1.0.0
paths: {}
swagger: "2.0"
